CREATE TABLE "NVR_MONITOR"."NVR_ALARM"
(
"ID" VARCHAR(36) NOT NULL,
"DEVICE_ID" VARCHAR(36) NOT NULL,
"ALARM_TYPE" VARCHAR(50) NOT NULL,
"ALARM_LEVEL" VARCHAR(20) NOT NULL,
"ALARM_TITLE" VARCHAR(200) NOT NULL,
"ALARM_CONTENT" TEXT,
"ALARM_VALUE" VARCHAR(100),
"STATUS" VARCHAR(20) DEFAULT 'PENDING',
"HANDLER_ID" VARCHAR(36),
"HANDLE_TIME" DATETIME(6),
"HANDLE_CONTENT" VARCHAR(500),
"CREATE_TIME" DATETIME(6) DEFAULT SYSDATE,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE OR REPLACE  INDEX "NVR_MONITOR"."IDX_ALARM_DEVICE_ID" ON "NVR_MONITOR"."NVR_ALARM"("DEVICE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "NVR_MONITOR"."IDX_ALARM_STATUS" ON "NVR_MONITOR"."NVR_ALARM"("STATUS" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "NVR_MONITOR"."IDX_ALARM_CREATE_TIME" ON "NVR_MONITOR"."NVR_ALARM"("CREATE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "NVR_MONITOR"."NVR_DEVICE"
(
"ID" VARCHAR(36) NOT NULL,
"NAME" VARCHAR(100) NOT NULL,
"CODE" VARCHAR(50) NOT NULL,
"BRAND" VARCHAR(20) NOT NULL,
"DEVICE_MODEL" VARCHAR(100),
"IP_ADDRESS" VARCHAR(50) NOT NULL,
"PORT" INT DEFAULT 8000,
"USERNAME" VARCHAR(50),
"PASSWORD" VARCHAR(255),
"COMPANY_ID" VARCHAR(36) NOT NULL,
"CHANNEL_COUNT" INT DEFAULT 0,
"STATUS" VARCHAR(20) DEFAULT 'ACTIVE',
"IS_ONLINE" INT DEFAULT 0,
"LAST_ONLINE_TIME" DATETIME(6),
"LAST_OFFLINE_TIME" DATETIME(6),
"DEVICE_INFO" TEXT,
"DISK_USAGE_RATE" DECIMAL(5,2),
"REMARKS" VARCHAR(500),
"CREATE_TIME" DATETIME(6) DEFAULT SYSDATE,
"UPDATE_TIME" DATETIME(6) DEFAULT SYSDATE,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "NVR_MONITOR"."NVR_DEVICE_STATUS"
(
"ID" VARCHAR(36) NOT NULL,
"DEVICE_ID" VARCHAR(36) NOT NULL,
"CPU_USAGE" DECIMAL(5,2),
"MEMORY_USAGE" DECIMAL(5,2),
"DISK_TOTAL" DECIMAL(10,2),
"DISK_USED" DECIMAL(10,2),
"DISK_FREE" DECIMAL(10,2),
"DISK_USAGE_RATE" DECIMAL(5,2),
"DEVICE_TEMPERATURE" DECIMAL(5,2),
"RECORDING_STATUS" VARCHAR(20),
"CHANNEL_ONLINE_COUNT" INT,
"CHANNEL_TOTAL_COUNT" INT,
"NETWORK_STATUS" VARCHAR(20),
"SYSTEM_TIME" DATETIME(6),
"RAW_DATA" TEXT,
"CREATE_TIME" DATETIME(6) DEFAULT SYSDATE,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE OR REPLACE  INDEX "NVR_MONITOR"."IDX_DEVICE_STATUS_DEVICE_ID" ON "NVR_MONITOR"."NVR_DEVICE_STATUS"("DEVICE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "NVR_MONITOR"."IDX_DEVICE_STATUS_TIME" ON "NVR_MONITOR"."NVR_DEVICE_STATUS"("CREATE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "NVR_MONITOR"."SYS_COMPANY"
(
"ID" VARCHAR(36) NOT NULL,
"NAME" VARCHAR(100) NOT NULL,
"CODE" VARCHAR(50) NOT NULL,
"PARENT_ID" VARCHAR(36),
"ADDRESS" VARCHAR(500),
"CONTACT_PERSON" VARCHAR(50),
"CONTACT_PHONE" VARCHAR(20),
"STATUS" VARCHAR(10) DEFAULT '1',
"REMARKS" VARCHAR(500),
"CREATE_TIME" DATETIME(6) DEFAULT SYSDATE,
"UPDATE_TIME" DATETIME(6) DEFAULT SYSDATE,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "NVR_MONITOR"."SYS_CONFIG"
(
"ID" VARCHAR(36) NOT NULL,
"CONFIG_KEY" VARCHAR(100) NOT NULL,
"CONFIG_VALUE" TEXT,
"CONFIG_TYPE" VARCHAR(50),
"DESCRIPTION" VARCHAR(200),
"STATUS" VARCHAR(10) DEFAULT '1',
"CREATE_TIME" DATETIME(6) DEFAULT SYSDATE,
"UPDATE_TIME" DATETIME(6) DEFAULT SYSDATE,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("CONFIG_KEY")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "NVR_MONITOR"."SYS_OPER_LOG"
(
"ID" VARCHAR(36) NOT NULL,
"USER_ID" VARCHAR(36),
"OPER_TYPE" VARCHAR(50),
"OPER_CONTENT" TEXT,
"OPER_IP" VARCHAR(50),
"CREATE_TIME" DATETIME(6) DEFAULT SYSDATE,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE OR REPLACE  INDEX "NVR_MONITOR"."IDX_OPER_LOG_USER" ON "NVR_MONITOR"."SYS_OPER_LOG"("USER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "NVR_MONITOR"."IDX_OPER_LOG_TIME" ON "NVR_MONITOR"."SYS_OPER_LOG"("CREATE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "NVR_MONITOR"."SYS_USER"
(
"ID" VARCHAR(36) NOT NULL,
"USERNAME" VARCHAR(50) NOT NULL,
"PASSWORD" VARCHAR(255) NOT NULL,
"REAL_NAME" VARCHAR(50),
"PHONE" VARCHAR(20),
"EMAIL" VARCHAR(100),
"ROLE" VARCHAR(20) DEFAULT 'USER',
"COMPANY_ID" VARCHAR(36),
"STATUS" VARCHAR(10) DEFAULT '1',
"LAST_LOGIN_TIME" DATETIME(6),
"CREATE_TIME" DATETIME(6) DEFAULT SYSDATE,
"UPDATE_TIME" DATETIME(6) DEFAULT SYSDATE,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("USERNAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

